/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wedding;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Fajar
 */
public class SelectedPemesanan extends javax.swing.JInternalFrame {

    /**
     * Creates new form SelectedPemesanan
     */
    public SelectedPemesanan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblLihat = new javax.swing.JTable();
        btnBack = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setTitle("Layanan Yang Sudah Dipesan");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });

        tblLihat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Tipe Layanan", "Kuantitas", "Harga per Kuantitas", "Keterangan"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLihat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblLihatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblLihat);

        btnBack.setText("Kembali");
        btnBack.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBackMouseClicked(evt);
            }
        });

        btnDelete.setText("Hapus");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBack)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(btnDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
        // TODO add your handling code here:
        fillTable();
    }//GEN-LAST:event_formInternalFrameOpened

    private void btnBackMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBackMouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        DetailPemesanan detailpesan = new DetailPemesanan();
        MainFrame.mdiMainMenu.add(detailpesan);
        detailpesan.setVisible(true);
    }//GEN-LAST:event_btnBackMouseClicked
    private void fillTable()
    {
        DefaultTableModel model = new DefaultTableModel(){
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
        };
        tblLihat.setModel(model);
        model.addColumn("Kode Layanan");
        model.addColumn("Tipe Layanan");
        model.addColumn("Kuantitas"); 
        model.addColumn("Harga Per Kuantitas");
        model.addColumn("Keterangan");
        Koneksi conn = new Koneksi();
        Connection kon=conn.conn();
        Statement stm;
        ResultSet rs;
        try{
            String sql = "SELECT ms_layanan.kodeLayanan, ms_tipelayanan.tipeLayanan,"
  + "dtl_tr_pemesanan.qtyLayanan, ms_layanan.hargaSatuan, dtl_tr_pemesanan.keterangan FROM ms_layanan " +
"INNER JOIN ms_tipelayanan ON ms_tipelayanan.kodeTipeLayanan=ms_layanan.kodeTipeLayanan " +
"INNER JOIN dtl_tr_pemesanan ON dtl_tr_pemesanan.kodeLayanan=ms_layanan.kodeLayanan"
                    + " AND dtl_tr_pemesanan.kodePemesanan = '"+conn.kodepesan+"'";
            stm = kon.createStatement();
            rs = stm.executeQuery(sql);
            while(rs.next()){
                Object [] o = new Object[5];
                o[0] = rs.getString("ms_layanan.kodeLayanan");
                o[1] = rs.getString("ms_tipelayanan.tipeLayanan");
                o[2] = rs.getString("dtl_tr_pemesanan.qtyLayanan");
                o[3] = rs.getString("ms_layanan.hargaSatuan");
                o[4] = rs.getString("dtl_tr_pemesanan.keterangan");
                model.addRow(o);
            }
         } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
        Koneksi conn = new Koneksi();
        Connection kon=conn.conn();
        Statement stm;
        try{
            String sql = "DELETE FROM dtl_tr_pemesanan WHERE `kodePemesanan` = '"+conn.kodepesan+"' AND`kodeLayanan` = '"+kodeLayanan+"'";
            stm = kon.createStatement();
            stm.executeUpdate(sql);
            fillTable();
            JOptionPane.showMessageDialog(null, "Penghapusan Berhasil");
                
         } catch (SQLException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteMouseClicked
    int kodeLayanan;
    private void tblLihatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblLihatMouseClicked
        // TODO add your handling code here:
        int i = tblLihat.getSelectedRow();
        TableModel model = tblLihat.getModel();
        String temp;
        temp = model.getValueAt(i, 0).toString();
        kodeLayanan = Integer.parseInt(temp);
    }//GEN-LAST:event_tblLihatMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDelete;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblLihat;
    // End of variables declaration//GEN-END:variables
}
